### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/website#54]
Also Document forms settings

**Comment by Allen616** [comment]
Here is some background information on how to get the form to work.

https://github.com/StefMa/hugo-fresh/issues/66

**Comment by Allen616** [comment]
@jacebrowning do you have a preference on how to set up contact form?

**Comment by jacebrowning** [comment]
If the contact form is simply going to send us an email, we could use a [`mailto`](https://css-tricks.com/snippets/html/mailto-links/) link.

Otherwise, a [Google Form](https://forestry.io/blog/5-ways-to-handle-forms-on-your-static-site/#google-forms-https-www-google-com-forms-about) embedded on the site hooked up to some Slack automation could work well.

**Comment by Allen616** [comment]
Thanks for the ideas and links. I ended up using formspree.io to stay consistent with the current design of the site.
